### ISSUE TITLE
[DE34] chef cookbook replacing sshd_config

### ISSUE THREAD

**Issue by jcannava** [rcbops/chef-cookbooks#326]
I've going through the private cloud setup and I see that your
openssh cookbook allows for all the items to be configured... which is
good.  Except by default you drop a 3 line config that effectively
disables sftp-server.

Would be really nice if you weren't just replacing the file with a
populated template, specially since your not configuring anything as I
believe those 3 entries are defaults in most major distributions.

Ideally, I'd suggest doing the same interface but using Augeas on the
backend, but I haven't tried that with chef.  The augeasprovider for
Puppet makes this very nice.  Here is the doc for reference:
https://github.com/raphink/augeasproviders/blob/master/docs/examples/sshd_config.md

**Comment by mancdaz** [comment]
This is generally a design principle of how chef operates.  Chef does not provide an easy way to interact using an augeas-like mechanism to edit files rather than dropping whole files on top.

Also, this is about the ssh cookbook which is owned and maintained by opscode, and the default sshd_config is dropped in by a template that lives there.  Any bug (and I'm not sure this is a bug) would need to be files against that cookbook.

**Comment by gregswift** [comment]
breaking the default on the OS, regardless of the method, is bad.  upstream (openssh) doesn't configure sftp by default, but every distribution i've used (debian and redhat families) provide it.  So i'll get around to filing a bug there against opscode's.
