### ISSUE TITLE
[DE38] Graphite missing dependency on RHEL 6.4

### ISSUE THREAD

**Issue by doublerr** [rcbops/chef-cookbooks#329]
Forum post:
https://privatecloudforums.rackspace.com/viewtopic.php?f=4&t=366

Error:
Error executing action `install` on resource 'package[bitmap]'

The following packages were not found in the RHEL repositories:
xbitmaps-1.1.1-4.ram1.x86_64.rpm
bitmap-fonts-compat-0.3-15.el6.noarch.rpm
bitmap-miscfixed-fonts-0.3-15.el6.noarch.rpm
bitmap-fangsongti-fonts-0.3-15.el6.noarch.rpm
bitmap-console-fonts-0.3-15.el6.noarch.rpm

After installing the packages, the user was able to successfully run chef-client with the graphite role

**Comment by galstrom21** [comment]
Pulling info from the linked forum post

# 

On RHEL 6.4 bitmap package has a dep on xbitmap which does not appear to be in the RHEL repos.

User installed xbitmap and required deps from:

```
ftp://rpmfind.net/linux/sourceforge/r/ra/ramonelinux/Rel_0.96/releases/x86_64/packages/xbitmaps-1.1.1-4.ram1.x86_64.rpm
ftp://rpmfind.net/linux/centos/6.4/os/x86_64/Packages/bitmap-fonts-compat-0.3-15.el6.noarch.rpm
ftp://rpmfind.net/linux/centos/6.4/os/x86_64/Packages/bitmap-miscfixed-fonts-0.3-15.el6.noarch.rpm
ftp://rpmfind.net/linux/centos/6.4/os/x86_64/Packages/bitmap-fangsongti-fonts-0.3-15.el6.noarch.rpm
ftp://rpmfind.net/linux/centos/6.4/os/x86_64/Packages/bitmap-console-fonts-0.3-15.el6.noarch.rpm
```

**Comment by mattt416** [comment]
Hi @doublerr,

I've just spun up a new RHEL 6.4 instance to test and didn't encounter the issue reported.  However, I do believe I know what the problem is.  On my instance, bitmap (from EPEL) requires in xbitmaps (the actual package it pulls in is xorg-x11-xbitmaps), and xorg-x11-xbitmaps is only available in rhel-x86_64-server-optional-6.  From http://fedoraproject.org/wiki/EPEL:

```
NOTE for RHN users.
You need to also enable the 'optional' repository to use EPEL packages as they depend on packages in that    repository.
```

I suspect GeoKM doesn't have that repo enabled, which is why bitmap wasn't able to pull in xbitmaps (xorg-x11-xbitmaps).  http://fedoraproject.org/wiki/EPEL outlines how to go about getting that enabled via RHN.

Please give us a shout if GeoKM experiences further issues.

-Matt

**Comment by toddmichael** [comment]
I ran into similar problem on CentOS 6.3 this evening.  The solution for me was to amend my graphite wrapper cookbook so that it looked like this:

``` ruby
# graphite pukes due to inability to install bitmap package
# requires epel, but not added by graphite so adding here
# https://github.com/rcbops/chef-cookbooks/issues/329
include_recipe "yum::epel"

include_recipe "graphite"
```

Thanks @matt416 for showing me the path to success. Cheers!

::toddmichael
