### ISSUE TITLE
/etc/fstab is clobbered 

### ISSUE THREAD

**Issue by ringohasadd** [rcbops/chef-cookbooks#333]
After assigning the role role[swift-object-server], role[swift-container-server], role[swift-account-server] to a machine the /etc/fstab file becomes clobbered and fails to boot.

Specifically:
"LABEL=cloudimg-rootfs / ext4 defaults 0 0" becomes 
"LABEL=cloudimg-rootfs /ext4defaults00"

Looking at: chef-cookbooks/cookbooks/swift/providers/mounts.rb it appears this possibly could be causing it??? but I'm not sure. 

Instance type  "Ubuntu 12.04.1 Precise (cloudimg)"
Swift cookbook version: 1.0.12

**Comment by mattt416** [comment]
Hi @ringohasadd,

We use these swift roles all the time on Ubuntu 12.04 and have yet to encounter this issue.  I have just built a swift installation on Ubuntu 12.04 and am unable to replicate what you are seeing.  You are correct in that the fstab may be modified in swift/providers/mounts.rb, however the only modifications to fstab that I can see taking place there are the addition and deletion of entries:

https://github.com/rcbops-cookbooks/swift/blob/master/providers/mounts.rb#L88
https://github.com/rcbops-cookbooks/swift/blob/master/providers/mounts.rb#L138

I am going to go ahead and close this issue since I cannot replicate it, however please do update the issue if you are able to provide us with any additional information.  Output from your chef-client run, chef-client/server versions, etc. would all be helpful.

On a side note, the swift cookbook is now at version 1.0.16, but I do not see any changes between 1.0.12 and 1.0.16 that would break /etc/fstab.

Kind Regards,
Matt
