### ISSUE TITLE
[DE121]: [nova-network]: nova-manage network create still gets run even if networks have already been created

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#381]
In nova-network/providers/networks.rb there is a not_if statement that doesn't seem to work quite so well, resulting in the chef run continuously trying to recreate the network ranges.

For example, when the networks are created by executing this:
nova-manage network create --multi_host=T --label=private --fixed_range_v4=10.70.0.0/16 --num_networks=32 --network_size=32 --bridge=br100 --bridge_interface=eth0.100 --dns1=8.8.8.8 --dns2=8.8.4.4

with "ipv4_cidr": "10.70.0.0/16"

The line in the recipe tries to execute:
not_if "nova-manage network list | grep 10.70.0.0/16"

This doesn't work as there is no '10.70.0.0/16' network - they're each /27 networks.

I've resolved this temporarily by changing:

not_if "nova-manage network list | grep #{new_resource.fixed_range}"

to:

only_if "nova-manage network list | grep 'No networks found'"

This is not ideal, as it's not exactly what the intention is behind the original design... but it's better than continual errors in the chef run.

**Comment by andymcc** [comment]
The nova-manage network create command uses args (num_networks/network_size) which aren't possible when using the nova api. In general we should probably adjust this to use the nova api, since we'd be moving towards using "OpenStack" networking, I've simply removed the ability to specify num networks/network size - this will mean the "not if" command will succeed so networks shouldn't be created on each run.

https://github.com/rcbops-cookbooks/nova-network/pull/19
