### ISSUE TITLE
[DE152]: RFC: Add attributes to allow keystone to use SSL

### ISSUE THREAD

**Issue by JCallicoat** [rcbops/chef-cookbooks#423]
http://docs.openstack.org/trunk/openstack-compute/admin/content/keystone-ssl.html

**Comment by mancdaz** [comment]
Hi @JCallicoat 

We're actually already working on a story to present all API services with https, using apache & mod_wsgi, since not all services support https natively like keystone.  The unified approach for all services will be easier to manage, so I'm going to close this particular request.

Cheers
@mancdaz
