### ISSUE TITLE
[DE168]: Glance images do not replicate with HA controllers

### ISSUE THREAD

**Issue by jwalcik** [rcbops/chef-cookbooks#430]
Using the grizzly branch. Images/snapshots are not being replicated between the two controllers. The glance-image-sync.py is being executed by cron, but it is returning an error:

root@controller01:/var/log# /var/lib/glance/glance-image-sync.py both
Traceback (most recent call last):
  File "/var/lib/glance/glance-image-sync.py", line 218, in <module>
    main(sys.argv)
  File "/var/lib/glance/glance-image-sync.py", line 212, in main
    _sync_images(glance_api_cfg, image_sync_cfg, conn, exchange)
  File "/var/lib/glance/glance-image-sync.py", line 156, in _sync_images
    msg.payload['payload']['id'])
KeyError: 'id'
root@controller01:/var/log#

The error message is the same regardless of which of the controllers I execute the script on.

**Comment by mattt416** [comment]
Hi there @jwalcik,

This issue was fixed in https://github.com/rcbops/glance-image-sync/commit/dacf5e585884c7a694bd36a9e5cc2752ef2f9513 and https://github.com/rcbops-cookbooks/glance/commit/e274052497a8a9762a7a554b5bb3fa74d3ff064c.  Can you please ensure you have the latest grizzly glance cookbook?

Thanks!

-Matt
