### ISSUE TITLE
[DE202]: vips aren't templated into glance config files on first chef run

### ISSUE THREAD

**Issue by brc** [rcbops/chef-cookbooks#464]
The addresses configured in the `vips` environment override aren't put into the config files until I run chef a second time (on `ha-controller[12]` roles).  It uses the local address (as would be returned by `get_bind_endpoint()`) the first time around.

**Comment by mancdaz** [comment]
@invsblduck which config files do you mean?  keepalived/haproxy, or the various api config files?

If the latter, then certainly this would be expected behaviour the first time you run ha-controller1. Sometimes if you run ha-controller2 before the results from ha-controller1 have converged, you might see this there too.

**Comment by brc** [comment]
i mean the api files.
on `ha-controller2`.
after `ha-controller1` has successfully converged twice.

only the second convergence on `ha-controller2` results in the keystone/mysql/rabbit vips being put into `cinder/api-paste.ini`, `nova/api-paste.ini`, `glance/glance-api-paste.ini`, etc.

**Comment by brc** [comment]
Found a bug in `RCB#get_access_endpoint`.
Code gating now.

**Comment by mancdaz** [comment]
fixed in https://github.com/rcbops-cookbooks/osops-utils/pull/115
