### ISSUE TITLE
[DE209]: Setup reverse proxy for public access via HTTPS

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#473]
Something to note - when doing this it's essential to set "AllowEncodedSlashes On" in the Apache Reverse Proxy configuration for Swift, otherwise you end up with issues uploading subfolders.

**Comment by hughsaunders** [comment]
Hi, 
Thanks again for your suggestion. We recognise the need for SSL endpoints, but are currently working on a different strategy. Instead of putting a proxy in front of the API servers, we are adding functionality to run the API servers within apache via WSGI, this way apache can provided SSL endpoints.

**Comment by odyssey4me** [comment]
@andymcc I believe you're working on the Apache/WSGI SSL endpoint enhancement. Any news? If not then I'll be reworking the Apache Reverse Proxy endpoint access and submitting it some time soon. If so, I'd like to give your work a run and help bake it a little, if necessary.
