### ISSUE TITLE
[DE232]: [nova] xvpvncproxy / novncproxy in nova.conf

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#498]
There should be an attribute that allows you to select whether to use xvpvncproxy or novncproxy which has the effect of only deploying the configuration for the one that is being used.

At the moment both options are implemented in nova.conf, on the haproxy, etc.

**Comment by andymcc** [comment]
Slightly bigger issue - the nova-xvpvncproxy package doesn't have an upstart script. https://bugs.launchpad.net/ubuntu/+source/nova/+bug/1197163

So really at the moment only novnc is working, but I'll look at separating them out (and ensuring ha-proxy is only setup for the service if its actually installed/meant to be running etc),  so that you can select to enable/disable them as required. The xvpvncproxy package isn't even installed at this point.

**Comment by jcannava** [comment]
@odyssey4me I'm marking this as won't fix and closing at this time. While we understand that both options are implemented the lack of an upstream package/upstart configuration for xvpvncproxy makes it hard for me to see how selection would make a difference here.

Of course if you have a patch for it we would happily accept it.

**Comment by odyssey4me** [comment]
@jcannava @andymcc Yeah, it's not urgent. Quite honestly a simple method for me considering that neither of us (it would seem) make use of xvpvncproxy is to remove the options altogether. An alternative approach would be to effectively negate the config options (thereby overriding whatever defaults nova puts in).

Of course we could 'fix' the brokenness, but I'm wary of taking on technical debt when no-one using these cookbooks is actually using the packages.

For now I'm just living with the superfluous configs. It's harmless enough.
