### ISSUE TITLE
[DE236]: Openstack YUM repo not overrideable

### ISSUE THREAD

**Issue by galstrom21** [rcbops/chef-cookbooks#504]
https://github.com/rcbops-cookbooks/osops-utils/blob/grizzly/recipes/packages.rb#L31-L37

This should be attributed out like the apt repo bit:

https://github.com/rcbops-cookbooks/osops-utils/blob/grizzly/recipes/packages.rb#L31-L37

**Comment by mancdaz** [comment]
Hi @galstrom21 

What do you need to do here?  We actually should be removing this (yum repo) block altogether for grizzly since the openstack packages now come directly from epel.

But maybe we need a (by default empty) attribute that can be used to provide an alternative repo if you want to use one that has packages that supercede those in epel?

**Comment by mancdaz** [comment]
see https://github.com/rcbops-cookbooks/osops-utils/pull/124

**Comment by mancdaz** [comment]
yeah so grizzly does not come from epel.  ignore that.

**Comment by mancdaz** [comment]
all done
