### ISSUE TITLE
[mysql-openstack] Disabling binlogs during install breaks replication on cookbook upgrades

### ISSUE THREAD

**Issue by DavidWittman** [rcbops/chef-cookbooks#515]
rcbops-cookbooks/mysql-openstack#47 introduced some changes which break compatibility with older installs. More specifically, it inadvertently disables MySQL binary logging on pre-existing installations which causes replication to break on HA builds which update to newer versions of the cookbooks.

This happens because the `cookbook_file` resource for the conf.d configuration which enables binary logging happens within the `node["mysql"]["myid"].nil? == true` conditional, which is only true on the first run. Moving the cookbook_file resource outside of the conditional at the end of the install may be a valid fix in this case, but I have yet to test it.

**Comment by mancdaz** [comment]
Hi @DavidWittman 

Thanks for this.  I think I didn't put it outside the conditional at the end because I wanted to ensure the replication user setup statements were captured in the binlog, which happens inside the first conditional on the setup of master 1.  I will work on getting a fix in that resolves both issues.

Cheers
@mancdaz

**Comment by zfeldstein** [comment]
This issue was fixed in: 

https://github.com/rcbops-cookbooks/mysql-openstack/commit/02db7deff91d0a4aba5161244fe72c2ef0b45748
