### ISSUE TITLE
[mysql-openstack]: mysql.server_id is not set on node in Folsom -> Grizzly upgrade

### ISSUE THREAD

**Issue by JCallicoat** [rcbops/chef-cookbooks#527]
In an HA Folsom -> Grizzly upgrade, mysql.myid is set on the first controller, so
mysql.tunable.server_id never gets set.

https://github.com/rcbops-cookbooks/mysql-openstack/blob/master/recipes/server.rb#L53

**Comment by git-harry** [comment]
@JCallicoat 

The Folsom cookbook uses node.override which explains why server_id is not set. This was changed in Grizzly so that it does get set.

If myid is set there should be no need to run that block of code again. What is the issue you are seeing with the server_id not being set?

Regards,
git-harry

**Comment by DavidWittman** [comment]
@git-harry `myid` is set, but because server_id was set with `node.override` and not `node.set`, the value for MySQL's server ID is not a persistent node attribute, so it is lost when the package upgrades and the template is regenerated (or at some other point in the Chef run). This causes server_id to default to 0, which effectively disables replication.

**Comment by git-harry** [comment]
@DavidWittman thanks for the update. I've added a check to make sure the server_id is set.

https://github.com/rcbops-cookbooks/mysql-openstack/pull/51

**Comment by JCallicoat** [comment]
@git-harry Any reason not to set `server_id` it to `myid` if `myid` is set?

**Comment by git-harry** [comment]
@JCallicoat server_id was not originally equal to myid - https://github.com/rcbops-cookbooks/mysql-openstack/commit/b6fa9162f952824cf2142ed2e461fe2218d6733e

**Comment by JCallicoat** [comment]
@git-harry To my knowledge they were always the same. Check out lines 80 and 117 in server.rb on b6fa916.

**Comment by git-harry** [comment]
@JCallicoat - the commit I link to shows that originally:

node.override["mysql"]["tunable"]["server_id"] = get_ip_for_net(mysql_network).gsub(/./, '')

**Comment by JCallicoat** [comment]
@git-harry You're right! I totally missed that and jumped straight to the file. :turtle:

**Comment by Apsu** [comment]
https://github.com/rcbops-cookbooks/mysql-openstack/commit/94f86e32e10cbbf6816b3cb6f116ce24acaa0527 make feex
