### ISSUE TITLE
[DE270]: Monit stops monitoring rabbitmq-server

### ISSUE THREAD

**Issue by JCallicoat** [rcbops/chef-cookbooks#546]
I haven't quite worked out how this happens, but somehow the rabbit pidfile (/var/run/rabbitmq/pid) is either missing, or has a stale pid in it, but rabbit _is_ running in another beam.smp process.

So monit sees the service as down since it's monitoring the pidfile, tries to restart rabbit and fails (since rabbit actually is running and bound to the port), repeats for 5 cycles until monit finally unmonitors it.

/var/log/syslog.5.gz:Aug 22 17:39:09 controller01.<scrubbed> monit[22344]: 'rabbitmq-server' service restarted 5 times within 5 cycles(s) - unmonitor

Then, sometime later, rabbit actually does go down, and it stays down until we manually intervene.

Changing the monit conf (/etc/monit/conf.d/rabbitmq-server.conf) from pidfile to matching temporarily works around the issue, but the root of the problem seems to be whatever is causing the stale/missing pidfile.

**Comment by claco** [comment]
@JCallicoat Matching is how we used to do it, then we changed it to pid. I wished I remembered why exactly. This may have been done because of pending merge of this ticket: http://tickets.opscode.com/browse/COOK-2705

See the Rally card for DE69, and also https://github.com/rcbops/chef-cookbooks/issues/355

The actual change was here: https://github.com/rcbops-cookbooks/rabbitmq-openstack/commit/38c4ad6a941a380a559ac0d5905fbc6591ee872a

I want to say that because keepalive was false, rabbitmq would down/up, causing a new pid, that causes monit to create out, and/or some version of that around ha.

**Comment by claco** [comment]
Is this related to https://github.com/rcbops/chef-cookbooks/issues/669 ? And @invsblduck did all your monit changes fix this issue?

(changed to 669)

**Comment by brc** [comment]
@claco didn't touch the rabbit stuff.
However I see it's removed altogether in `master`:

``` diff
commit bca20d1c87eb7ed7c0832bf809e6fb82e6f7330e

    remove rabbitmq from the services that monit watches

diff --git a/openstack-monitoring/recipes/rabbitmq-server.rb b/openstack-monitoring/recipes/rabbitmq-server.rb
index b921af3..1feb110 100644
--- a/openstack-monitoring/recipes/rabbitmq-server.rb
+++ b/openstack-monitoring/recipes/rabbitmq-server.rb
@@ -20,9 +20,7 @@ include_recipe "monitoring"
 if node.recipe?("rabbitmq-openstack::server")
   platform_options = node["rabbitmq"]["platform"]
   monitoring_procmon "rabbitmq-server" do
-    pid_file "/var/run/rabbitmq/pid"
-    service_name=platform_options["rabbitmq_service"]
-    script_name service_name
+    action :remove
   end
```

**Comment by claco** [comment]
@invsblduck and I meant the monit part of that title, not rabbit. At one point in the past, we flip flopped from by name to by pid, and likely back.

**Comment by breu** [comment]
This can probably go back in for @Apsu's HA work.  I added this because the HA failover scripts for my implementation were restarting rabbitmq-server on the node that was transitioning away from master.

**Comment by claco** [comment]
So, back in timey times, this was a procname match instead of pid...  https://github.com/rcbops-cookbooks/openstack-monitoring/blob/ad3f3ee9e042bea47d118a6f6e38b734b4267665/recipes/rabbitmq-server.rb#L30

I can't remember why I moved it. But the rabbit pid has always been an evil thing.

@JCallicoat @rackerjoe Should I simply re-add the patch above now that the @Apsu HA is workings? Or should I instead ra-add the procname version? I honestly have no idea which to do or the ramifications of either, other than the work here is minimal to do either.

**Comment by brc** [comment]
@claco, The monit config for rabbit has actually always used a pid (ever since Jason added it).  Line 30 you linked above is actually the collectd `monitoring_metric`.  Take a look at line 23 instead (https://github.com/rcbops-cookbooks/openstack-monitoring/blob/ad3f3ee9e042bea47d118a6f6e38b734b4267665/recipes/rabbitmq-server.rb#L23).

**Comment by breu** [comment]
The root cause of this problem isn't the fact that monit can't monitor the pid file correctly but actually that two restarts of the rabbitmq service in quick succession can actually cause a race condition where the second restart removes the valid pid file for the first running instance and then tries to restart which of course fails because another is already running.  This was the reason for removing this check in the first place when I was working on the HA stuff as I was restarting the rabbitmq-server on the state transition to backup which, if monit triggered at the same time, would cause this race condition.  Since we are not shipping that solution as the default we can add back in the monit monitor.

**Comment by claco** [comment]
@invsblduck Actually, wrong repo.  https://github.com/rcbops-cookbooks/rabbitmq-openstack/commit/90919ab356ecc5bb733b0d01362858e6416e850b

It used to be regex. Then I moved it to pidfile assuming the keepalive change would go in. Then it moved from rabbitmq to monitoring. Then pid file was a trash because of this race condition. Shenanigans!

**Comment by claco** [comment]
I will simply re-add this back in tomorrow and not try to understand the historical roller coaster. Then I shall blame @rackerjoe for everything.

**Comment by brc** [comment]
Ahh that was before it got moved to `openstack-monitoring`.  Carry on sir.
