### ISSUE TITLE
[DE304]: [nova] apache2/wsgi for osapi_compute not working

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#587]
@andymcc I'm not sure what's going wrong here but if I enable the ssl scheme for nova-api then the api doesn't work properly. Whenever I try to boot an instance the status stays stuck at 'scheduling' and never goes further.

As a test I switched the scheme back to http and adjusted the apache site config to:

```
Listen 192.168.4.62:8774
<VirtualHost 192.168.4.62:8774>
    WSGIScriptAlias / /etc/apache2/wsgi/nova-api-os-compute
    WSGIDaemonProcess nova-osapi user=nova group=nova processes=3 threads=10 python-path=/usr/share/pyshared/nova
    WSGIProcessGroup nova-osapi

    ErrorLog /var/log/nova/osapi.log
    LogLevel debug
    CustomLog /var/log/nova/osapi.log combined
</VirtualHost>
```

But with this config it still doesn't work. However, if I disable the site and restart the normal service then it works as it should.

Any idea what could be going wrong here?

Additional info:
1. a 'nova list' works when the service is running behind apache
2. when doing a 'nova boot' and running the service behind apache, the scheduler never receives the notification from the api service to kick off the new server build
3. there are no debug logs for the osapi service, only apache is logging

**Comment by zfeldstein** [comment]
I've narrowed this down a bit... It looks like when using the apache wsgi config the api is publishing messages to rabbitmq on the wrong exchange. It should send the build request to the "nova" exchange using the "scheduler" routing key. Instead it's using the "openstack" exchange using the "scheduler" routing key, which is why the scheduler never picks up the request and fails to schedule the build. 

I setup a rabbitmq trace of a server build talking directly to nova-api-os-compute, as well as a trace of a server build talking to the apache wsgi setup.  

Here is the GIST of the request when talking directly to nova:

https://gist.github.com/jrcloud/6772680#file-gistfile1-txt-L5

Here is the GIST of the rabbit trace when talking to apache/wsgi:

https://gist.github.com/jrcloud/6772684#file-gistfile1-txt-L4

The exchange is getting the default value  for some reason when using apache/wsgi, which is specified here:

https://github.com/openstack/nova/blob/master/nova/openstack/common/rpc/__init__.py#L69

If I change that default to nova and kick off a build using the apache/wsgi setup it completes successfully.

I'll dig on this a bit more to determine why we are not seeing the same behavior from the wsgi setup as we do when using nova-api.

**Comment by odyssey4me** [comment]
Excellent debugging. It appears that the control exchange is meant to be setup here:

https://github.com/openstack/nova/blob/master/nova/config.py#L33

The issue is definitely in the wsgi file itself. The configuration parameters for the app are not being set correctly on startup.

The following adjusted wsgi content outputs the right control_exchange, but something else still isn't right.

``` python
from nova.openstack.common import log as logging
from oslo.config import cfg
from nova import config
from paste import deploy

config_files = ['/etc/nova/api-paste.ini', '/etc/nova/nova.conf']
config.parse_args([], default_config_files=config_files)
logging.setup("nova")
CONF = cfg.CONF

conf = config_files[0]
name = "osapi_compute"

print "********** config debug **********"
import pprint
pprint.pprint(CONF.project)
pprint.pprint(CONF.control_exchange)
print "********** config debug **********"

options = deploy.appconfig('config:%s' % conf, name=name)

application = deploy.loadapp('config:%s' % conf, name=name)
```

**Comment by zfeldstein** [comment]
I used a modified version of the wsgi file you posted:

from nova.openstack.common import log as logging
from nova import config
from paste import deploy

LOG = logging.getLogger(**name**)
logging.setup("nova")

config_files = ['/etc/nova/api-paste.ini', '/etc/nova/nova.conf']

config.parse_args([], default_config_files=config_files)

conf = config_files[0]
name = "osapi_compute"

options = deploy.appconfig('config:%s' % conf, name=name)

application = deploy.loadapp('config:%s' % conf, name=name)

I've tested this and I'm not seeing any issues. Can you elaborate on what else you're seeing that is not behaving normally? If you see any issues while using the config I posted, let me know. Otherwise I am going to send a PR to correct the config. Thanks for catching this issue.

**Comment by zfeldstein** [comment]
https://github.com/rcbops-cookbooks/nova/pull/345

**Comment by zfeldstein** [comment]
merged:

https://github.com/rcbops-cookbooks/nova/commit/3b4d1014cc2c1144d5a9ea7672ba90e7a937bb71
