### ISSUE TITLE
[osops-utils]: allow use of an arbitrary (non-chef-deployed) mysql installation/IP

### ISSUE THREAD

**Issue by mancdaz** [rcbops/chef-cookbooks#597]
Right now, all of the various service config files get populated with the mysql IP address by searching for the 'mysql-master' role.  If >1 are found, the VIP must be defined in the environment and is then used.  If =1 is found, the IP of that node is used.

We should make it possible for a user to utilise an already deployed mysql server/cluster, and provide an arbitrary IP for it to chef by passing the IP as an environment variable.  This would require short circuiting the current search logic that requires at least one mysql-master role to exist.

**Comment by odyssey4me** [comment]
:+1: This could be done in the much earlier cookbooks, but the option got broken somewhere along the way.

**Comment by claco** [comment]
Yeah, seems like a consuming cookbook issue. If attr.emty? then do the search. Can we blame @hughsaunders and his osops_searchyness? :-)

**Comment by hughsaunders** [comment]
@claco I don't think we can blame me ;-) however I tend to agree that the issue probably needs to be fixed in the recipes doing the searching rather than the osops-utils search function.

**Comment by ragsns** [comment]
I think this will be useful (or a must have) to be able to use RPC on top of existing MySQL installations.

**Comment by claco** [comment]
@mancdaz @odyssey4me @ragsns @hughsaunders Do we have any sort of scope for this? Or is this someone where we should  do this across the board with every service?

**Comment by claco** [comment]
@mancdaz I see why you picked osops now. https://github.com/rcbops-cookbooks/glance/blob/master/recipes/glance-common.rb#L178

This pattern is everywhere. I'm hesitant to do any reliance on the role name though. Maybe I can, but just wrap that in a recipe help method and convert all of the cookbooks to use that instead of get_access_endpoint.  I'm also tempted to follow that pattern and add a ["host"] attribute in each service cookbook. If it's set, use it, if not, then search. But this also means one would have to set this all over the various servers in attributes.  While correct. Also not user friendly.  Thoughts?

**Comment by claco** [comment]
@mancdaz @odyssey4me @ragsns @hughsaunders 

This seems to be somewhat of a rabbit hole. Not because of `get_access_endpoint` which is pretty easy to abstract calls to, but because of this: 

```
https://github.com/rcbops-cookbooks/osops-utils/blob/master/libraries/database.rb#L28
```

They don't just need to specify another non-chef ip, but also user/pass because it's not going to chef managed, so there's no settings attributes to fetch for server_password.

What's a good set of attribute names that aren't going to be confused with the service settings themselves in:

```
["mysql"]["services"]["db"] = {"host" => ..., "name" => ...}
```

And also not confused with the stock mysql recipe attributes?

Of course, I can abandon this path, and go back to changing every specific service cookbook to have it's own mysql ip/admin_user/admin_pass in attributes.

**Comment by claco** [comment]
Done. I'm sure there are edge cases buried at level that I do not know about.

`["unmanaged"]["mysql"]["host"]`  and `["server_root_password"]`  will override all the various cookbook uses of `get_mysql_endpoint` and `get_mysql_settings` in `osops-utils` as well as the `create_user_and_database` method.
