### ISSUE TITLE
notification_driver in Quantum

### ISSUE THREAD

**Issue by rpawlik** [rcbops/chef-cookbooks#637]
We need to be able to overwrite the "notification_driver" in quantum.conf. Please make an attribute for this.

**Comment by JCallicoat** [comment]
It should also probably default to `quantum.openstack.common.notifier.no_op_notifier` rather than `quantum.openstack.common.notifier.rpc_notifier` as quantum puts quite a few messages in the `notifications.info` queue (bound on the quantum exchange). These are never read, and it eventually begins effecting performance when the number of messages gets into the tens of thousands.

**Comment by DavidWittman** [comment]
I addressed this on master with the above PR. What's the procedure (if any) for backporting this to Grizzly?

**Comment by willkelly** [comment]
Rebase on v4.1.3rc branch and submit a pr to that branch.  We'll figure it out from there.
