### ISSUE TITLE
enable_metadata_network not templateable

### ISSUE THREAD

**Issue by cjoelrun** [rcbops/chef-cookbooks#878]
enable_metadata_network is in a templatable but not an attribute, so always false.

I'm still looking at the implications of setting false

``` bash
$ grep enable_metadata_network . -r
./cookbooks/nova-network/templates/default/dhcp_agent.ini.erb:enable_metadata_network = <%= @neutron_metadata_network %>
```

/etc/neutron/dhcp_agent.ini

```
##### METADATA OPTIONS #####                                                                                                                                                         
# DHCP server can assist with providing metadata support on isolated networks                                                                                                        
enable_isolated_metadata = True

# Allows serving metadata from a network when the cidr is 169.254.169.254/16.                                                                                                        
# To set this "True" it requires "enable_isolated_metadata = True"                                                                                                                   
enable_metadata_network = False
```

**Comment by Apsu** [comment]
We should clean up the Chef side a bit, but essentially, we never want to set enable_metadata_network to true in our view of the world. It is designed for having a dedicated Neutron network which is exclusively for carrying 169.254/16 traffic, destined for the Nova metadata API. This was basically designed for cases where you might be running your metadata somewhere finicky to get to from the host network, so this gave you the option of tunneling/VLAN/etc it through a Neutron network. Since we don't even give you toggles to federate to other metadata systems or setups, it's "harmful at best" to make this a toggle.
